# Mosquitto MQTT Broker Configuration

# Escucha en el puerto 1883 para conexiones MQTT
listener 1883
allow_anonymous true

# Configuración de persistencia para mantener los mensajes y el estado del broker
persistence true
persistence_location /mosquitto/data/

# Configuración de logging para registrar eventos y errores
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout